---
- hosts: all
  user: jayakarthi
  sudo: true
  gather_facts: no
  tasks:
     - name: System update
       update_apt_cache: true
       #apt: update_cache=yes
       sudo: yes

#    - name: System update
#      command: /usr/bin/apt-get update
#      sudo: yes
