---
- hosts: all
  user: jayakarthi
  sudo: true
  gather_facts: no
  tasks:
     - name: System update
       apt: upgrade=dist
       sudo: yes

#    - name: System update
#      command: /usr/bin/apt-get update
#      sudo: yes
