---
- hosts: 127.0.0.1 
  user: jayakarthi
  sudo: true
  gather_facts: no
  tasks:
     - name: System update
       apt: update_cache=yes
       sudo: yes

#    - name: System update
#      command: /usr/bin/apt-get update
#      sudo: yes
